name: bibliaia
description: Bible IA - Intelligent Bible App
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_markdown: ^0.7.7

  cupertino_icons: ^1.0.8

  # Estado
  flutter_riverpod: ^3.0.3

  # HTTP
  dio: ^5.9.0

  # Logs
  logger: ^2.6.1

  # Internacionalização
  intl: ^0.20.2

  # Banco local
  sqflite: ^2.4.2

  # Caminhos do SQLite
  path: ^1.9.1

  # Preferências
  shared_preferences: ^2.5.3
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Pacote adicionado para habilitar a geração automática de ícones
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/json/

# Configuração do gerador de ícones
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/app_icon.png
  remove_alpha_ios: true
  #git commit -m "" git push origin develop:main --force   s
  # open ios/Runner.xcworkspace 
  #flutter build ipa 